apiVersion: v1
entries:
  harness-common:
  - apiVersion: v2
    appVersion: 0.0.0
    created: "2026-04-10T18:13:46.347450117Z"
    description: Helm Common library for Harness Helm Charts
    digest: 22f5a053147119cc91162495de9515aa096eadfa82bf710874af0370d85435fa
    name: harness-common
    type: library
    urls:
    - https://harness.github.io/helm-common/charts/harness-common-1.5.4-develop.23.tgz
    version: 1.5.4-develop.23
  - apiVersion: v2
    appVersion: 0.0.0
    created: "2026-04-10T18:13:46.345363835Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.16.1
    description: Helm Common library for Harness Helm Charts
    digest: a2c6cffeaec9c04b0fc6e00fe6f1df94314469f1a9530dd8c6479533a80fa116
    name: harness-common
    type: library
    urls:
    - https://harness.github.io/helm-common/charts/harness-common-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.0.0
    created: "2026-04-10T18:13:46.344621919Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.16.1
    description: Helm Common library for Harness Helm Charts
    digest: 8f27fb45413e78bc8173c35e64e1c01ebed42efbd1efe4ec7dc2f3f82dcc7e16
    name: harness-common
    type: library
    urls:
    - https://harness.github.io/helm-common/charts/harness-common-0.1.0.tgz
    version: 0.1.0
generated: "2026-04-10T18:13:46.343738194Z"
