{{- if .Values.secrets }}
---
# Test: secrets rendered as environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-secrets-env-test
data:
  env: |
    {{- include "harnesscommon.renderSecretsAsEnvironmentVariables" (dict "ctx" $) | nindent 4 }}
{{- end }}
