{{- if .Values.secrets }}
---
# Test: kubernetesSecrets rendered as environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-secrets-env-test
data:
  env: |
    {{- include "harnesscommon.renderSecretsAsEnvironmentVariables" (dict "ctx" $) | nindent 4 }}
---
# Test: kubernetesSecrets rendered as projected volumes (fileSecret)
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-secrets-volumes-test
data:
  volumes: |
    {{- include "harnesscommon.renderSecretsAsVolumes" (dict "ctx" $) | nindent 4 }}
{{- end }}
