{{- if and .Values.global .Values.global.services }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: services-env-test
data:
  env: |
{{ include "harnesscommon.services.renderServiceSecretsEnv" (dict "ctx" $) | indent 4 }}
---
{{- include "harnesscommon.services.generateServiceExternalSecrets" (dict "ctx" $) }}
{{- end }}
